imports:
    - { resource: "@SyliusBetterSeoPlugin/Resources/config/app.yaml" }
    - { resource: "@SyliusBetterSeoPlugin/Resources/config/services.yaml" }
    - { resource: "@SyliusBetterSeoPlugin/Resources/config/resources.yaml" }
