sylius_resource:
    resources:
        sylius_better_seo_plugin.seo:
            driver: doctrine/orm
            classes:
                model: JoppeDc\SyliusBetterSeoPlugin\Entity\Seo
                interface: JoppeDc\SyliusBetterSeoPlugin\Entity\SeoInterface
            translation:
                classes:
                    model: JoppeDc\SyliusBetterSeoPlugin\Entity\SeoTranslation
                    interface: JoppeDc\SyliusBetterSeoPlugin\Entity\SeoTranslationInterface
        sylius_better_seo_plugin.seo_image:
            classes:
                model: JoppeDc\SyliusBetterSeoPlugin\Entity\SeoImage
                interface: JoppeDc\SyliusBetterSeoPlugin\Entity\SeoImageInterface
                form: JoppeDc\SyliusBetterSeoPlugin\Form\Type\SeoImageType

liip_imagine:
    filter_sets:
        sylius_shop_seo_image:
            filters:
                thumbnail: { size: [1200, 630], mode: outbound }
