services:
    joppedc_sylius_better_seo_plugin.product.type_extension:
        class: JoppeDc\SyliusBetterSeoPlugin\Form\ProductTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductType, priority: -5 }

    joppedc_sylius_better_seo_plugin.taxon.type_extension:
        class: JoppeDc\SyliusBetterSeoPlugin\Form\TaxonTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\TaxonomyBundle\Form\Type\TaxonType, priority: -5 }

    joppedc_sylius_better_seo_plugin.seo.form.type:
        class: JoppeDc\SyliusBetterSeoPlugin\Form\Type\SeoType
        arguments:
            $dataClass: '%sylius_better_seo_plugin.model.seo.class%'
        tags:
            - { name: form.type }

    joppedc_sylius_better_seo_plugin.seo_translation.form.type:
        class: JoppeDc\SyliusBetterSeoPlugin\Form\Type\SeoTranslationType
        arguments:
            $dataClass: '%sylius_better_seo_plugin.model.seo_translation.class%'
        tags:
            - { name: form.type }

    joppedc_sylius_better_seo_plugin.seo_image.type.form.type:
        class: JoppeDc\SyliusBetterSeoPlugin\Form\Type\SeoImageType
        arguments:
            $dataClass: '%sylius_better_seo_plugin.model.seo_image.class%'
        tags:
            - { name: form.type }

    joppedc_sylius_better_seo_plugin.listener.images_upload:
        class: JoppeDc\SyliusBetterSeoPlugin\EventListener\SeoTranslationImagesUploadListener
        parent: sylius.listener.images_upload
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: kernel.event_listener, event: sylius.product.pre_create, method: uploadMedia }
            - { name: kernel.event_listener, event: sylius.taxon.pre_create, method: uploadMedia }
            - { name: kernel.event_listener, event: sylius.product.pre_update, method: uploadMedia }
            - { name: kernel.event_listener, event: sylius.taxon.pre_update, method: uploadMedia }
